Repository emulsify-ds/emulsify-cli, pull requests merged in 2021-11, with the labels that each got.

#37 docs: fix typo
  USAGE.md
Labels: Status: Passes code review

#33 Memoize the findFileInCurrentPath method with fileName being the key
  .husky/pre-push
  src/util/fs/findFileInCurrentPath.test.ts
  src/util/fs/findFileInCurrentPath.ts
Labels: Status: Review Needed

#34 feat(30): add ability to specify init success messages per platform
  src/handlers/init.ts
  src/util/platform/getInitSuccessMessageForPlatform.test.ts
  src/util/platform/getInitSuccessMessageForPlatform.ts
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review

#35 feat(32): add a systemInstall hook execution step
  src/handlers/systemInstall.ts
  src/lib/constants.ts
Labels: 👍 Ready for Review

#40 docs: moved the install command under the installation heading
  README.md
Labels: 👍 Ready for Review
