Repository emulsify-ds/emulsify-cli, pull requests merged in 2024-09, with the labels that each got.

#288 feat: Add no-platform starter as default init setup
  src/handlers/init.test.ts
  src/handlers/init.ts
  src/index.ts
  src/schemas/variant.json
  src/types/_emulsifyProjectConfig.d.ts
  src/types/_system.d.ts
  src/types/_variant.d.ts
  src/util/getAvailableStarters.test.ts
  src/util/getAvailableStarters.ts
  src/util/getGitRepoNameFromUrl.test.ts
  src/util/platform/getInitSuccessMessageForPlatform.ts
  src/util/platform/getNoPlatformInfo.test.ts
  src/util/platform/getNoPlatformInfo.ts
  src/util/platform/getPlatformInfo.test.ts
  src/util/platform/getPlatformInfo.ts
  src/util/system/getAvailableSystems.test.ts
  src/util/system/getAvailableSystems.ts
Labels: 🎉 Passes Functional Review, 🎉 Passes Code Review, 🪄 Enhancement, 🎉 Ready to Merge

#294 Allow init command to run without parameters
  package-lock.json
  package.json
  src/handlers/init.test.ts
  src/handlers/init.ts
  src/index.ts
  src/util/system/getAvailableSystems.test.ts
  src/util/system/getAvailableSystems.ts
Labels: 👍 Ready for Review

#289 feat: Switch from chalk to colorette for better compatibility
  package-lock.json
  package.json
  src/lib/log.ts
  src/util/platform/getInitSuccessMessageForPlatform.ts
Labels: 👍 Ready for Review

#296 2.x cleanup commands
  src/index.ts
  src/util/cache/cloneIntoCache.test.ts
  src/util/cache/getCachedItemPath.ts
  src/util/getRepositoryLatestTag.test.ts
  src/util/getRepositoryLatestTag.ts
Labels: 👁 Review in progress
